sudo: required
services:
  - docker

before_install:
  - docker build -t jonricaurte/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jonricaurte/react-test npm run test -- --coverage

after_success:
  - docker build -t jonricaurte/multi-client ./client
  - docker build -t jonricaurte/multi-nginx ./nginx
  - docker build -t jonricaurte/multi-server ./server
  - docker build -t jonricaurte/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jonricaurte/multi-client
  - docker push jonricaurte/multi-nginx
  - docker push jonricaurte/multi-server
  - docker push jonricaurte/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-168452182586'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    # prettier-ignore
    secure: "$AWS_SECRET_KEY"
